### ISSUE TITLE
Strategize/customize map view for many markers at single point.

### ISSUE THREAD

**Issue by mnyrop** [cul/biggert_static#7]
We must rid Boston of this horror:
 
![leaflet-map](http://oi63.tinypic.com/2m85zy8.jpg)

Which is currently handled by: `L.markerClusterGroup({spiderfyOnMaxZoom: true}` ([options](https://github.com/Leaflet/Leaflet.markercluster#all-options)).

Thoughts?

**Comment by er-k** [comment]
this is a thing of beauty.

how do i recreate this? i'm not seeing it.

**Comment by mnyrop** [comment]
There needs to be some way to generate a popup list of markers on the same spot...?
*or* instead of popups at all, results for a given area could be appended as div result elements via jquery underneath the map...? 

No amount of zooming will untangle points with the exact same coordinates, sadly.
